# Generated by Django 6.0.3 on 2026-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
