# Generated by Django 6.0.3 on 2026-04-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_colors_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='products',
            name='favorited_by',
        ),
    ]
