# Generated by Django 6.0.3 on 2026-04-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_products_colors_remove_products_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
